spring:
  application:
    name: lab6-spring-security
  datasource:
    password: postgrespw
    url: jdbc:postgresql://localhost:49153/lab6-spring-security
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  redis:
    host: localhost
    port: 6379
    timeout: 60000
    database: 0
server:
  port: 8080
